Repository haskell/actions, pull requests merged in 2023-01, with the labels that each got.

#152 Merge local dependabot.yml files into global one
  .github/dependabot.yml
  hlint-run/.github/README.md
  hlint-run/.github/dependabot.yml
  hlint-run/.nvmrc
  hlint-setup/.github/dependabot.yml
  hlint-setup/.nvmrc
Labels: re: continuous integration (CI)

#164 Add a new workflow to generate release on tag push
  .github/workflows/release.yml
Labels: pr: squash-me, re: releases, re: continuous integration (CI)

#146 Fix #29: new input `cabal-update: false` to skip 'cabal update'
  .github/workflows/workflow.yml
  setup/README.md
  setup/__tests__/project-with-hackage-dependency/Main.hs
  setup/__tests__/project-with-hackage-dependency/Setup.hs
  setup/__tests__/project-with-hackage-dependency/project-with-hackage-dependency.cabal
  setup/action.yml
  setup/dist/index.js
  setup/lib/opts.d.ts
  setup/lib/opts.js
  setup/lib/setup-haskell.js
  setup/src/opts.ts
  setup/src/setup-haskell.ts
Labels: re: cabal

#165 Fix #130: ensure cabal installdir is in the PATH
  .github/workflows/workflow.yml
  setup/__tests__/project/project.cabal
  setup/dist/index.js
  setup/lib/setup-haskell.js
  setup/src/setup-haskell.ts
Labels: bug, re: cabal

#172 Update ghcup to 0.1.19.0
  setup/dist/index.js
  setup/lib/versions.json
  setup/src/versions.json
Labels: dependencies, re: ghcup

#175 Add support for ghcup release channel
  .github/workflows/workflow.yml
  setup/README.md
  setup/action.yml
  setup/dist/index.js
  setup/lib/installer.d.ts
  setup/lib/installer.js
  setup/lib/opts.d.ts
  setup/lib/opts.js
  setup/lib/setup-haskell.js
  setup/src/installer.ts
  setup/src/opts.ts
  setup/src/setup-haskell.ts
Labels: re: ghcup
