Repository haskell/actions, pull requests merged in 2023-05, with the labels that each got.

#206 use ghcup on windows (clone of #192)
  .github/workflows/workflow.yml
  setup/dist/index.js
  setup/lib/installer.js
  setup/lib/opts.d.ts
  setup/lib/opts.js
  setup/lib/setup-haskell.js
  setup/src/installer.ts
  setup/src/opts.ts
  setup/src/setup-haskell.ts
Labels: help wanted, pr: squash-me, platform: windows, re: ghcup

#244 Add GHC 9.4.5
  setup/README.md
  setup/dist/index.js
  setup/lib/versions.json
  setup/src/versions.json
Labels: dependencies

#252 add explicit coercion where TypeSsript 5 became more strict
  hlint-run/package.json
  hlint-run/src/run.ts
  hlint-run/yarn.lock
Labels: dependencies, re: hlint
